appname: "redis-ctl"
entrypoints:
    web:
        cmd: "python main.py"
        ports:
            - "8000/tcp"
    daemon:
        cmd: "python daemon.py"
    taskrunner:
        cmd: "python task_runner.py"
    releaselock:
        cmd: "python release_task_lock.py"
build: "pip install -r requirements.txt"
